title: cd-sebento-scratch-3-scratch2
hero_image: images/banner.png
description: cd-sebento-scratch-3-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2018-12-20"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
